export default letters = [
  [
    { ka: "ア", hi: "あ", en: "A", ru: "А " },
    { ka: "イ", hi: "い", en: "I", ru: "И " },
    { ka: "ウ", hi: "う", en: "U", ru: "У " },
    { ka: "エ", hi: "え", en: "E", ru: "Э " },
    { ka: "オ", hi: "お", en: "O", ru: "О " },
  ],
  [
    { ka: "カ", hi: "か", en: "KA", ru: "КА" },
    { ka: "キ", hi: "き", en: "KI", ru: "КИ" },
    { ka: "ク", hi: "く", en: "KU", ru: "КУ" },
    { ka: "ケ", hi: "け", en: "KE", ru: "КЭ" },
    { ka: "コ", hi: "こ", en: "KO", ru: "КО" },
  ],
  [
    { ka: "サ", hi: "さ", en: "SA ", ru: "CА" },
    { ka: "シ", hi: "し", en: "SHI", ru: "ШИ" },
    { ka: "ス", hi: "す", en: "SU ", ru: "СУ" },
    { ka: "セ", hi: "せ", en: "SE ", ru: "СЕ" },
    { ka: "ソ", hi: "そ", en: "SO ", ru: "СО" },
  ],
  [
    { ka: "タ", hi: "た", en: "TA ", ru: "ТА" },
    { ka: "チ", hi: "ち", en: "CHI", ru: "ЧИ" },
    { ka: "ツ", hi: "つ", en: "TSU ", ru: "ТУ" },
    { ka: "テ", hi: "て", en: "TE ", ru: "ТЭ" },
    { ka: "ト", hi: "と", en: "TO ", ru: "ТО" },
  ],
  [
    { ka: "ナ", hi: "な", en: "NA", ru: "НА" },
    { ka: "ニ", hi: "に", en: "NI", ru: "НИ" },
    { ka: "ヌ", hi: "ぬ", en: "NU", ru: "НУ" },
    { ka: "ネ", hi: "ね", en: "NE", ru: "НЭ" },
    { ka: "ノ", hi: "の", en: "NO", ru: "НО" },
  ],
  [
    { ka: "ハ", hi: "は", en: "HA", ru: "ХА" },
    { ka: "ヒ", hi: "ひ", en: "HI", ru: "ХИ" },
    { ka: "フ", hi: "ふ", en: "FU", ru: "ФУ" },
    { ka: "ヘ", hi: "へ", en: "HE", ru: "ХЭ" },
    { ka: "ホ", hi: "ほ", en: "HO", ru: "ХО" },
  ],
  [
    { ka: "マ", hi: "ま", en: "MA", ru: "МА" },
    { ka: "ミ", hi: "み", en: "MI", ru: "МИ" },
    { ka: "ム", hi: "む", en: "MU", ru: "МУ" },
    { ka: "メ", hi: "め", en: "ME", ru: "МЭ" },
    { ka: "モ", hi: "も", en: "MO", ru: "МО" },
  ],
  [
    { ka: "ヤ", hi: "や", en: "YA", ru: "Я" },
    { ka: "ユ", hi: "ゆ", en: "YU", ru: "Ю" },
    { ka: "ヨ", hi: "よ", en: "YO", ru: "Ё" },
  ],
  [
    { ka: "ラ", hi: "ら", en: "RA", ru: "РА" },
    { ka: "リ", hi: "り", en: "RI", ru: "РИ" },
    { ka: "ル", hi: "る", en: "RU", ru: "РУ" },
    { ka: "レ", hi: "れ", en: "RE", ru: "РЭ" },
    { ka: "ロ", hi: "ろ", en: "RO", ru: "РО" },
  ],
  [
    { ka: "ワ", hi: "わ", en: "WA", ru: "ВА" },
    { ka: "ヲ", hi: "を", en: "WO", ru: "ВО" },
  ],
  [
    { ka: "ガ", hi: "が", en: "GA", ru: "ГА" },
    { ka: "ギ", hi: "ぎ", en: "GI", ru: "ГИ" },
    { ka: "グ", hi: "ぐ", en: "GU", ru: "ГУ" },
    { ka: "ゲ", hi: "げ", en: "GE", ru: "ГЭ" },
    { ka: "ゴ", hi: "ご", en: "GO", ru: "ГО" },
  ],
  [
    { ka: "ザ", hi: "ざ", en: "ZA", ru: "ЗА" },
    { ka: "ジ", hi: "じ", en: "JI", ru: "ДЗИ" },
    { ka: "ズ", hi: "ず", en: "ZU", ru: "ДЗУ" },
    { ka: "ゼ", hi: "ぜ", en: "ZE", ru: "ДЗЭ" },
    { ka: "ゾ", hi: "ぞ", en: "ZO", ru: "ДЗО" },
  ],
  [
    { ka: "ダ", hi: "だ", en: "DA", ru: "ДА" },
    { ka: "ヂ", hi: "ぢ", en: "JI", ru: "ДЗИ" },
    { ka: "ヅ", hi: "づ", en: "ZU", ru: "ДЗУ" },
    { ka: "デ", hi: "で", en: "DE", ru: "ДЭ" },
    { ka: "ド", hi: "ど", en: "DO", ru: "ДО" },
  ],
  [
    { ka: "バ", hi: "ば", en: "BA", ru: "БА" },
    { ka: "ビ", hi: "び", en: "BI", ru: "БИ" },
    { ka: "ブ", hi: "ぶ", en: "BU", ru: "БУ" },
    { ka: "ベ", hi: "べ", en: "BE", ru: "БЭ" },
    { ka: "ボ", hi: "ぼ", en: "BO", ru: "БО" },
  ],
  [
    { ka: "パ", hi: "ぱ", en: "PA", ru: "ПА" },
    { ka: "ピ", hi: "ぴ", en: "PI", ru: "ПИ" },
    { ka: "プ", hi: "ぷ", en: "PU", ru: "ПУ" },
    { ka: "ペ", hi: "ぺ", en: "PE", ru: "ПЭ" },
    { ka: "ポ", hi: "ぽ", en: "PO", ru: "ПО" },
  ],
];
