/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable import/order */

// basic
import HA from "./light/H-A.svg";
import HFU from "./light/H-FU.svg";
import HHI from "./light/H-HI.svg";
import HKA from "./light/H-KA.svg";
import HKO from "./light/H-KO.svg";
import HME from "./light/H-ME.svg";
import HMU from "./light/H-MU.svg";
import HNE from "./light/H-NE.svg";
import HNU from "./light/H-NU.svg";
import HRE from "./light/H-RE.svg";
import HRU from "./light/H-RU.svg";
import HSHI from "./light/H-SHI.svg";
import HTA from "./light/H-TA.svg";
import HTSU from "./light/H-TSU.svg";
import HWE from "./light/H-WE.svg";
import HYA from "./light/H-YA.svg";
import HCHI from "./light/H-CHI.svg";
import HHA from "./light/H-HA.svg";
import HHO from "./light/H-HO.svg";
import HKE from "./light/H-KE.svg";
import HKU from "./light/H-KU.svg";
import HMI from "./light/H-MI.svg";
import HN from "./light/H-N.svg";
import HNI from "./light/H-NI.svg";
import HO from "./light/H-O.svg";
import HRI from "./light/H-RI.svg";
import HSA from "./light/H-SA.svg";
import HSO from "./light/H-SO.svg";
import HTE from "./light/H-TE.svg";
import HU from "./light/H-U.svg";
import HWI from "./light/H-WI.svg";
import HYO from "./light/H-YO.svg";
import HE from "./light/H-E.svg";
import HHE from "./light/H-HE.svg";
import HI from "./light/H-I.svg";
import HKI from "./light/H-KI.svg";
import HMA from "./light/H-MA.svg";
import HMO from "./light/H-MO.svg";
import HNA from "./light/H-NA.svg";
import HNO from "./light/H-NO.svg";
import HRA from "./light/H-RA.svg";
import HRO from "./light/H-RO.svg";
import HSE from "./light/H-SE.svg";
import HSU from "./light/H-SU.svg";
import HTO from "./light/H-TO.svg";
import HWA from "./light/H-WA.svg";
import HWO from "./light/H-WO.svg";
import HYU from "./light/H-YU.svg";

import HADARK from "./dark/H-A.svg";
import HFUDARK from "./dark/H-FU.svg";
import HHIDARK from "./dark/H-HI.svg";
import HKADARK from "./dark/H-KA.svg";
import HKODARK from "./dark/H-KO.svg";
import HMEDARK from "./dark/H-ME.svg";
import HMUDARK from "./dark/H-MU.svg";
import HNEDARK from "./dark/H-NE.svg";
import HNUDARK from "./dark/H-NU.svg";
import HREDARK from "./dark/H-RE.svg";
import HRUDARK from "./dark/H-RU.svg";
import HSHIDARK from "./dark/H-SHI.svg";
import HTADARK from "./dark/H-TA.svg";
import HTSUDARK from "./dark/H-TSU.svg";
import HWEDARK from "./dark/H-WE.svg";
import HYADARK from "./dark/H-YA.svg";
import HCHIDARK from "./dark/H-CHI.svg";
import HHADARK from "./dark/H-HA.svg";
import HHODARK from "./dark/H-HO.svg";
import HKEDARK from "./dark/H-KE.svg";
import HKUDARK from "./dark/H-KU.svg";
import HMIDARK from "./dark/H-MI.svg";
import HNDARK from "./dark/H-N.svg";
import HNIDARK from "./dark/H-NI.svg";
import HODARK from "./dark/H-O.svg";
import HRIDARK from "./dark/H-RI.svg";
import HSADARK from "./dark/H-SA.svg";
import HSODARK from "./dark/H-SO.svg";
import HTEDARK from "./dark/H-TE.svg";
import HUDARK from "./dark/H-U.svg";
import HWIDARK from "./dark/H-WI.svg";
import HYODARK from "./dark/H-YO.svg";
import HEDARK from "./dark/H-E.svg";
import HHEDARK from "./dark/H-HE.svg";
import HIDARK from "./dark/H-I.svg";
import HKIDARK from "./dark/H-KI.svg";
import HMADARK from "./dark/H-MA.svg";
import HMODARK from "./dark/H-MO.svg";
import HNADARK from "./dark/H-NA.svg";
import HNODARK from "./dark/H-NO.svg";
import HRADARK from "./dark/H-RA.svg";
import HRODARK from "./dark/H-RO.svg";
import HSEDARK from "./dark/H-SE.svg";
import HSUDARK from "./dark/H-SU.svg";
import HTODARK from "./dark/H-TO.svg";
import HWADARK from "./dark/H-WA.svg";
import HWODARK from "./dark/H-WO.svg";
import HYUDARK from "./dark/H-YU.svg";

// 2
import HBA from "./light/H-BA.svg";
import HBI from "./light/H-BI.svg";
import HBU from "./light/H-BU.svg";
import HDE from "./light/H-DE.svg";
import HDO from "./light/H-DO.svg";
import HGA from "./light/H-GA.svg";
import HGI from "./light/H-GI.svg";
import HGU from "./light/H-GU.svg";
import HZA from "./light/H-ZA.svg";
import HZO from "./light/H-ZO.svg";
import HBE from "./light/H-BE.svg";
import HBO from "./light/H-BO.svg";
import HDA from "./light/H-DA.svg";
import HDJI from "./light/H-DJI.svg";
import HDZU from "./light/H-DZU.svg";
import HGE from "./light/H-GE.svg";
import HGO from "./light/H-GO.svg";
import HJI from "./light/H-JI.svg";
import HZE from "./light/H-ZE.svg";
import HZU from "./light/H-ZU.svg";
// dark
import HBADARK from "./dark/H-BA.svg";
import HBIDARK from "./dark/H-BI.svg";
import HBUDARK from "./dark/H-BU.svg";
import HDEDARK from "./dark/H-DE.svg";
import HDODARK from "./dark/H-DO.svg";
import HGADARK from "./dark/H-GA.svg";
import HGIDARK from "./dark/H-GI.svg";
import HGUDARK from "./dark/H-GU.svg";
import HZADARK from "./dark/H-ZA.svg";
import HZODARK from "./dark/H-ZO.svg";
import HBEDARK from "./dark/H-BE.svg";
import HBODARK from "./dark/H-BO.svg";
import HDADARK from "./dark/H-DA.svg";
import HDJIDARK from "./dark/H-DJI.svg";
import HDZUDARK from "./dark/H-DZU.svg";
import HGEDARK from "./dark/H-GE.svg";
import HGODARK from "./dark/H-GO.svg";
import HJIDARK from "./dark/H-JI.svg";
import HZEDARK from "./dark/H-ZE.svg";
import HZUDARK from "./dark/H-ZU.svg";

// 3
import HPA from "./light/H-PA.svg";
import HPE from "./light/H-PE.svg";
import HPI from "./light/H-PI.svg";
import HPO from "./light/H-PO.svg";
import HPU from "./light/H-PU.svg";
// 3 dark
import HPADARK from "./dark/H-PA.svg";
import HPEDARK from "./dark/H-PE.svg";
import HPIDARK from "./dark/H-PI.svg";
import HPODARK from "./dark/H-PO.svg";
import HPUDARK from "./dark/H-PU.svg";

import HCHA from "./light/H-CHA.svg";
import HCHU from "./light/H-CHU.svg";
import HHYO from "./light/H-HYO.svg";
import HKYA from "./light/H-KYA.svg";
import HKYU from "./light/H-KYU.svg";
import HMYO from "./light/H-MYO.svg";
import HNYA from "./light/H-NYA.svg";
import HNYU from "./light/H-NYU.svg";
import HRYO from "./light/H-RYO.svg";
import HSHA from "./light/H-SHA.svg";
import HSHU from "./light/H-SHU.svg";
import HCHO from "./light/H-CHO.svg";
import HHYA from "./light/H-HYA.svg";
import HHYU from "./light/H-HYU.svg";
import HKYO from "./light/H-KYO.svg";
import HMYA from "./light/H-MYA.svg";
import HMYU from "./light/H-MYU.svg";
import HNYO from "./light/H-NYO.svg";
import HRYA from "./light/H-RYA.svg";
import HRYU from "./light/H-RYU.svg";
import HSHO from "./light/H-SHO.svg";
// DARK
import HCHADARK from "./dark/H-CHA.svg";
import HCHUDARK from "./dark/H-CHU.svg";
import HHYODARK from "./dark/H-HYO.svg";
import HKYADARK from "./dark/H-KYA.svg";
import HKYUDARK from "./dark/H-KYU.svg";
import HMYODARK from "./dark/H-MYO.svg";
import HNYADARK from "./dark/H-NYA.svg";
import HNYUDARK from "./dark/H-NYU.svg";
import HRYODARK from "./dark/H-RYO.svg";
import HSHADARK from "./dark/H-SHA.svg";
import HSHUDARK from "./dark/H-SHU.svg";
import HCHODARK from "./dark/H-CHO.svg";
import HHYADARK from "./dark/H-HYA.svg";
import HHYUDARK from "./dark/H-HYU.svg";
import HKYODARK from "./dark/H-KYO.svg";
import HMYADARK from "./dark/H-MYA.svg";
import HMYUDARK from "./dark/H-MYU.svg";
import HNYODARK from "./dark/H-NYO.svg";
import HRYADARK from "./dark/H-RYA.svg";
import HRYUDARK from "./dark/H-RYU.svg";
import HSHODARK from "./dark/H-SHO.svg";

// basic
import KA from "./light/K-A.svg";
import KFU from "./light/K-FU.svg";
import KHI from "./light/K-HI.svg";
import KKA from "./light/K-KA.svg";
import KKO from "./light/K-KO.svg";
import KME from "./light/K-ME.svg";
import KMU from "./light/K-MU.svg";
import KNE from "./light/K-NE.svg";
import KNU from "./light/K-NU.svg";
import KRE from "./light/K-RE.svg";
import KRU from "./light/K-RU.svg";
import KSHI from "./light/K-SHI.svg";
import KTA from "./light/K-TA.svg";
import KTSU from "./light/K-TSU.svg";
import KWE from "./light/K-WE.svg";
import KYA from "./light/K-YA.svg";
import KCHI from "./light/K-CHI.svg";
import KHA from "./light/K-HA.svg";
import KHO from "./light/K-HO.svg";
import KKE from "./light/K-KE.svg";
import KKU from "./light/K-KU.svg";
import KMI from "./light/K-MI.svg";
import KN from "./light/K-N.svg";
import KNI from "./light/K-NI.svg";
import KO from "./light/K-O.svg";
import KRI from "./light/K-RI.svg";
import KSA from "./light/K-SA.svg";
import KSO from "./light/K-SO.svg";
import KTE from "./light/K-TE.svg";
import KU from "./light/K-U.svg";
import KWI from "./light/K-WI.svg";
import KYO from "./light/K-YO.svg";
import KE from "./light/K-E.svg";
import KHE from "./light/K-HE.svg";
import KI from "./light/K-I.svg";
import KKI from "./light/K-KI.svg";
import KMA from "./light/K-MA.svg";
import KMO from "./light/K-MO.svg";
import KNA from "./light/K-NA.svg";
import KNO from "./light/K-NO.svg";
import KRA from "./light/K-RA.svg";
import KRO from "./light/K-RO.svg";
import KSE from "./light/K-SE.svg";
import KSU from "./light/K-SU.svg";
import KTO from "./light/K-TO.svg";
import KWA from "./light/K-WA.svg";
import KWO from "./light/K-WO.svg";
import KYU from "./light/K-YU.svg";

import KADARK from "./dark/K-A.svg";
import KFUDARK from "./dark/K-FU.svg";
import KHIDARK from "./dark/K-HI.svg";
import KKADARK from "./dark/K-KA.svg";
import KKODARK from "./dark/K-KO.svg";
import KMEDARK from "./dark/K-ME.svg";
import KMUDARK from "./dark/K-MU.svg";
import KNEDARK from "./dark/K-NE.svg";
import KNUDARK from "./dark/K-NU.svg";
import KREDARK from "./dark/K-RE.svg";
import KRUDARK from "./dark/K-RU.svg";
import KSHIDARK from "./dark/K-SHI.svg";
import KTADARK from "./dark/K-TA.svg";
import KTSUDARK from "./dark/K-TSU.svg";
import KWEDARK from "./dark/K-WE.svg";
import KYADARK from "./dark/K-YA.svg";
import KCHIDARK from "./dark/K-CHI.svg";
import KHADARK from "./dark/K-HA.svg";
import KHODARK from "./dark/K-HO.svg";
import KKEDARK from "./dark/K-KE.svg";
import KKUDARK from "./dark/K-KU.svg";
import KMIDARK from "./dark/K-MI.svg";
import KNDARK from "./dark/K-N.svg";
import KNIDARK from "./dark/K-NI.svg";
import KODARK from "./dark/K-O.svg";
import KRIDARK from "./dark/K-RI.svg";
import KSADARK from "./dark/K-SA.svg";
import KSODARK from "./dark/K-SO.svg";
import KTEDARK from "./dark/K-TE.svg";
import KUDARK from "./dark/K-U.svg";
import KWIDARK from "./dark/K-WI.svg";
import KYODARK from "./dark/K-YO.svg";
import KEDARK from "./dark/K-E.svg";
import KHEDARK from "./dark/K-HE.svg";
import KIDARK from "./dark/K-I.svg";
import KKIDARK from "./dark/K-KI.svg";
import KMADARK from "./dark/K-MA.svg";
import KMODARK from "./dark/K-MO.svg";
import KNADARK from "./dark/K-NA.svg";
import KNODARK from "./dark/K-NO.svg";
import KRADARK from "./dark/K-RA.svg";
import KRODARK from "./dark/K-RO.svg";
import KSEDARK from "./dark/K-SE.svg";
import KSUDARK from "./dark/K-SU.svg";
import KTODARK from "./dark/K-TO.svg";
import KWADARK from "./dark/K-WA.svg";
import KWODARK from "./dark/K-WO.svg";
import KYUDARK from "./dark/K-YU.svg";

// 2
import KBA from "./light/K-BA.svg";
import KBI from "./light/K-BI.svg";
import KBU from "./light/K-BU.svg";
import KDE from "./light/K-DE.svg";
import KDO from "./light/K-DO.svg";
import KGA from "./light/K-GA.svg";
import KGI from "./light/K-GI.svg";
import KGU from "./light/K-GU.svg";
import KZA from "./light/K-ZA.svg";
import KZO from "./light/K-ZO.svg";
import KBE from "./light/K-BE.svg";
import KBO from "./light/K-BO.svg";
import KDA from "./light/K-DA.svg";
import KDJI from "./light/K-DJI.svg";
import KDZU from "./light/K-DZU.svg";
import KGE from "./light/K-GE.svg";
import KGO from "./light/K-GO.svg";
import KJI from "./light/K-JI.svg";
import KZE from "./light/K-ZE.svg";
import KZU from "./light/K-ZU.svg";
// dark
import KBADARK from "./dark/K-BA.svg";
import KBIDARK from "./dark/K-BI.svg";
import KBUDARK from "./dark/K-BU.svg";
import KDEDARK from "./dark/K-DE.svg";
import KDODARK from "./dark/K-DO.svg";
import KGADARK from "./dark/K-GA.svg";
import KGIDARK from "./dark/K-GI.svg";
import KGUDARK from "./dark/K-GU.svg";
import KZADARK from "./dark/K-ZA.svg";
import KZODARK from "./dark/K-ZO.svg";
import KBEDARK from "./dark/K-BE.svg";
import KBODARK from "./dark/K-BO.svg";
import KDADARK from "./dark/K-DA.svg";
import KDJIDARK from "./dark/K-DJI.svg";
import KDZUDARK from "./dark/K-DZU.svg";
import KGEDARK from "./dark/K-GE.svg";
import KGODARK from "./dark/K-GO.svg";
import KJIDARK from "./dark/K-JI.svg";
import KZEDARK from "./dark/K-ZE.svg";
import KZUDARK from "./dark/K-ZU.svg";

// 3
import KPA from "./light/K-PA.svg";
import KPE from "./light/K-PE.svg";
import KPI from "./light/K-PI.svg";
import KPO from "./light/K-PO.svg";
import KPU from "./light/K-PU.svg";
// 3 dark
import KPADARK from "./dark/K-PA.svg";
import KPEDARK from "./dark/K-PE.svg";
import KPIDARK from "./dark/K-PI.svg";
import KPODARK from "./dark/K-PO.svg";
import KPUDARK from "./dark/K-PU.svg";

import KCHA from "./light/K-CHA.svg";
import KCHU from "./light/K-CHU.svg";
import KHYO from "./light/K-HYO.svg";
import KKYA from "./light/K-KYA.svg";
import KKYU from "./light/K-KYU.svg";
import KMYO from "./light/K-MYO.svg";
import KNYA from "./light/K-NYA.svg";
import KNYU from "./light/K-NYU.svg";
import KRYO from "./light/K-RYO.svg";
import KSHA from "./light/K-SHA.svg";
import KSHU from "./light/K-SHU.svg";
import KCHO from "./light/K-CHO.svg";
import KHYA from "./light/K-HYA.svg";
import KHYU from "./light/K-HYU.svg";
import KKYO from "./light/K-KYO.svg";
import KMYA from "./light/K-MYA.svg";
import KMYU from "./light/K-MYU.svg";
import KNYO from "./light/K-NYO.svg";
import KRYA from "./light/K-RYA.svg";
import KRYU from "./light/K-RYU.svg";
import KSHO from "./light/K-SHO.svg";
// DARK
import KCHADARK from "./dark/K-CHA.svg";
import KCHUDARK from "./dark/K-CHU.svg";
import KHYODARK from "./dark/K-HYO.svg";
import KKYADARK from "./dark/K-KYA.svg";
import KKYUDARK from "./dark/K-KYU.svg";
import KMYODARK from "./dark/K-MYO.svg";
import KNYADARK from "./dark/K-NYA.svg";
import KNYUDARK from "./dark/K-NYU.svg";
import KRYODARK from "./dark/K-RYO.svg";
import KSHADARK from "./dark/K-SHA.svg";
import KSHUDARK from "./dark/K-SHU.svg";
import KCHODARK from "./dark/K-CHO.svg";
import KHYADARK from "./dark/K-HYA.svg";
import KHYUDARK from "./dark/K-HYU.svg";
import KKYODARK from "./dark/K-KYO.svg";
import KMYADARK from "./dark/K-MYA.svg";
import KMYUDARK from "./dark/K-MYU.svg";
import KNYODARK from "./dark/K-NYO.svg";
import KRYADARK from "./dark/K-RYA.svg";
import KRYUDARK from "./dark/K-RYU.svg";
import KSHODARK from "./dark/K-SHO.svg";


const getImage = (key: string | undefined, iamgeStyle: Record<string, string | number>) => {

  if (key === undefined) return <HA style={iamgeStyle} />;

  switch (key.trim()) {
    // Basic
    case "H-A": return <HA style={ iamgeStyle } />;
    case "H-FU": return <HFU style={ iamgeStyle } />;
    case "H-HI": return <HHI style={ iamgeStyle } />;
    case "H-KA": return <HKA style={ iamgeStyle } />;
    case "H-KO": return <HKO style={ iamgeStyle } />;
    case "H-ME": return <HME style={ iamgeStyle } />;
    case "H-MU": return <HMU style={ iamgeStyle } />;
    case "H-NE": return <HNE style={ iamgeStyle } />;
    case "H-NU": return <HNU style={ iamgeStyle } />;
    case "H-RE": return <HRE style={ iamgeStyle } />;
    case "H-RU": return <HRU style={ iamgeStyle } />;
    case "H-SHI": return <HSHI style={ iamgeStyle } />;
    case "H-TA": return <HTA style={ iamgeStyle } />;
    case "H-TSU": return <HTSU style={ iamgeStyle } />;
    case "H-WE": return <HWE style={ iamgeStyle } />;
    case "H-YA": return <HYA style={ iamgeStyle } />;
    case "H-CHI": return <HCHI style={ iamgeStyle } />;
    case "H-HA": return <HHA style={ iamgeStyle } />;
    case "H-HO": return <HHO style={ iamgeStyle } />;
    case "H-KE": return <HKE style={ iamgeStyle } />;
    case "H-KU": return <HKU style={ iamgeStyle } />;
    case "H-MI": return <HMI style={ iamgeStyle } />;
    case "H-N": return <HN style={ iamgeStyle } />;
    case "H-NI": return <HNI style={ iamgeStyle } />;
    case "H-O": return <HO style={ iamgeStyle } />;
    case "H-RI": return <HRI style={ iamgeStyle } />;
    case "H-SA": return <HSA style={ iamgeStyle } />;
    case "H-SO": return <HSO style={ iamgeStyle } />;
    case "H-TE": return <HTE style={ iamgeStyle } />;
    case "H-U": return <HU style={ iamgeStyle } />;
    case "H-WI": return <HWI style={ iamgeStyle } />;
    case "H-YO": return <HYO style={ iamgeStyle } />;
    case "H-E": return <HE style={ iamgeStyle } />;
    case "H-HE": return <HHE style={ iamgeStyle } />;
    case "H-I": return <HI style={ iamgeStyle } />;
    case "H-KI": return <HKI style={ iamgeStyle } />;
    case "H-MA": return <HMA style={ iamgeStyle } />;
    case "H-MO": return <HMO style={ iamgeStyle } />;
    case "H-NA": return <HNA style={ iamgeStyle } />;
    case "H-NO": return <HNO style={ iamgeStyle } />;
    case "H-RA": return <HRA style={ iamgeStyle } />;
    case "H-RO": return <HRO style={ iamgeStyle } />;
    case "H-SE": return <HSE style={ iamgeStyle } />;
    case "H-SU": return <HSU style={ iamgeStyle } />;
    case "H-TO": return <HTO style={ iamgeStyle } />;
    case "H-WA": return <HWA style={ iamgeStyle } />;
    case "H-WO": return <HWO style={ iamgeStyle } />;
    case "H-YU": return <HYU style={ iamgeStyle } />;
    // Basic dark
    case "H-FU-DARK": return <HFUDARK style={ iamgeStyle } />;
    case "H-A-DARK": return <HADARK style={ iamgeStyle } />;
    case "H-HI-DARK": return <HHIDARK style={ iamgeStyle } />;
    case "H-KA-DARK": return <HKADARK style={ iamgeStyle } />;
    case "H-KO-DARK": return <HKODARK style={ iamgeStyle } />;
    case "H-ME-DARK": return <HMEDARK style={ iamgeStyle } />;
    case "H-MU-DARK": return <HMUDARK style={ iamgeStyle } />;
    case "H-NE-DARK": return <HNEDARK style={ iamgeStyle } />;
    case "H-NU-DARK": return <HNUDARK style={ iamgeStyle } />;
    case "H-RE-DARK": return <HREDARK style={ iamgeStyle } />;
    case "H-RU-DARK": return <HRUDARK style={ iamgeStyle } />;
    case "H-SHI-DARK": return <HSHIDARK style={ iamgeStyle } />;
    case "H-TA-DARK": return <HTADARK style={ iamgeStyle } />;
    case "H-TSU-DARK": return <HTSUDARK style={ iamgeStyle } />;
    case "H-WE-DARK": return <HWEDARK style={ iamgeStyle } />;
    case "H-YA-DARK": return <HYADARK style={ iamgeStyle } />;
    case "H-CHI-DARK": return <HCHIDARK style={ iamgeStyle } />;
    case "H-HA-DARK": return <HHADARK style={ iamgeStyle } />;
    case "H-HO-DARK": return <HHODARK style={ iamgeStyle } />;
    case "H-KE-DARK": return <HKEDARK style={ iamgeStyle } />;
    case "H-KU-DARK": return <HKUDARK style={ iamgeStyle } />;
    case "H-MI-DARK": return <HMIDARK style={ iamgeStyle } />;
    case "H-N-DARK": return <HNDARK style={ iamgeStyle } />;
    case "H-NI-DARK": return <HNIDARK style={ iamgeStyle } />;
    case "H-O-DARK": return <HODARK style={ iamgeStyle } />;
    case "H-RI-DARK": return <HRIDARK style={ iamgeStyle } />;
    case "H-SA-DARK": return <HSADARK style={ iamgeStyle } />;
    case "H-SO-DARK": return <HSODARK style={ iamgeStyle } />;
    case "H-TE-DARK": return <HTEDARK style={ iamgeStyle } />;
    case "H-U-DARK": return <HUDARK style={ iamgeStyle } />;
    case "H-WI-DARK": return <HWIDARK style={ iamgeStyle } />;
    case "H-YO-DARK": return <HYODARK style={ iamgeStyle } />;
    case "H-E-DARK": return <HEDARK style={ iamgeStyle } />;
    case "H-HE-DARK": return <HHEDARK style={ iamgeStyle } />;
    case "H-I-DARK": return <HIDARK style={ iamgeStyle } />;
    case "H-KI-DARK": return <HKIDARK style={ iamgeStyle } />;
    case "H-MA-DARK": return <HMADARK style={ iamgeStyle } />;
    case "H-MO-DARK": return <HMODARK style={ iamgeStyle } />;
    case "H-NA-DARK": return <HNADARK style={ iamgeStyle } />;
    case "H-NO-DARK": return <HNODARK style={ iamgeStyle } />;
    case "H-RA-DARK": return <HRADARK style={ iamgeStyle } />;
    case "H-RO-DARK": return <HRODARK style={ iamgeStyle } />;
    case "H-SE-DARK": return <HSEDARK style={ iamgeStyle } />;
    case "H-SU-DARK": return <HSUDARK style={ iamgeStyle } />;
    case "H-TO-DARK": return <HTODARK style={ iamgeStyle } />;
    case "H-WA-DARK": return <HWADARK style={ iamgeStyle } />;
    case "H-WO-DARK": return <HWODARK style={ iamgeStyle } />;
    case "H-YU-DARK": return <HYUDARK style={ iamgeStyle } />;
    // Dakuon
    case "H-BA": return <HBA style={ iamgeStyle } />;
    case "H-BI": return <HBI style={ iamgeStyle } />;
    case "H-BU": return <HBU style={ iamgeStyle } />;
    case "H-DE": return <HDE style={ iamgeStyle } />;
    case "H-DO": return <HDO style={ iamgeStyle } />;
    case "H-GA": return <HGA style={ iamgeStyle } />;
    case "H-GI": return <HGI style={ iamgeStyle } />;
    case "H-GU": return <HGU style={ iamgeStyle } />;
    case "H-ZA": return <HZA style={ iamgeStyle } />;
    case "H-ZO": return <HZO style={ iamgeStyle } />;
    case "H-BE": return <HBE style={ iamgeStyle } />;
    case "H-BO": return <HBO style={ iamgeStyle } />;
    case "H-DA": return <HDA style={ iamgeStyle } />;
    case "H-DJI": return <HDJI style={ iamgeStyle } />;
    case "H-DZU": return <HDZU style={ iamgeStyle } />;
    case "H-GE": return <HGE style={ iamgeStyle } />;
    case "H-GO": return <HGO style={ iamgeStyle } />;
    case "H-JI": return <HJI style={ iamgeStyle } />;
    case "H-ZE": return <HZE style={ iamgeStyle } />;
    case "H-ZU": return <HZU style={ iamgeStyle } />;
    // Dakuon dark
    case "H-BA-DARK": return <HBADARK style={ iamgeStyle } />;
    case "H-BI-DARK": return <HBIDARK style={ iamgeStyle } />;
    case "H-BU-DARK": return <HBUDARK style={ iamgeStyle } />;
    case "H-DE-DARK": return <HDEDARK style={ iamgeStyle } />;
    case "H-DO-DARK": return <HDODARK style={ iamgeStyle } />;
    case "H-GA-DARK": return <HGADARK style={ iamgeStyle } />;
    case "H-GI-DARK": return <HGIDARK style={ iamgeStyle } />;
    case "H-GU-DARK": return <HGUDARK style={ iamgeStyle } />;
    case "H-ZA-DARK": return <HZADARK style={ iamgeStyle } />;
    case "H-ZO-DARK": return <HZODARK style={ iamgeStyle } />;
    case "H-BE-DARK": return <HBEDARK style={ iamgeStyle } />;
    case "H-BO-DARK": return <HBODARK style={ iamgeStyle } />;
    case "H-DA-DARK": return <HDADARK style={ iamgeStyle } />;
    case "H-DJI-DARK": return <HDJIDARK style={ iamgeStyle } />;
    case "H-DZU-DARK": return <HDZUDARK style={ iamgeStyle } />;
    case "H-GE-DARK": return <HGEDARK style={ iamgeStyle } />;
    case "H-GO-DARK": return <HGODARK style={ iamgeStyle } />;
    case "H-JI-DARK": return <HJIDARK style={ iamgeStyle } />;
    case "H-ZE-DARK": return <HZEDARK style={ iamgeStyle } />;
    case "H-ZU-DARK": return <HZUDARK style={ iamgeStyle } />;
    // Handakuon
    case "H-PA": return <HPA style={ iamgeStyle } />;
    case "H-PE": return <HPE style={ iamgeStyle } />;
    case "H-PI": return <HPI style={ iamgeStyle } />;
    case "H-PO": return <HPO style={ iamgeStyle } />;
    case "H-PU": return <HPU style={ iamgeStyle } />;
    // Handakuon dark
    case "H-PA-DARK": return <HPADARK style={ iamgeStyle } />;
    case "H-PE-DARK": return <HPEDARK style={ iamgeStyle } />;
    case "H-PI-DARK": return <HPIDARK style={ iamgeStyle } />;
    case "H-PO-DARK": return <HPODARK style={ iamgeStyle } />;
    case "H-PU-DARK": return <HPUDARK style={ iamgeStyle } />;
    // 
    case "H-CHA": return <HCHA style={ iamgeStyle } />;
    case "H-CHU": return <HCHU style={ iamgeStyle } />;
    case "H-HYO": return <HHYO style={ iamgeStyle } />;
    case "H-KYA": return <HKYA style={ iamgeStyle } />;
    case "H-KYU": return <HKYU style={ iamgeStyle } />;
    case "H-MYO": return <HMYO style={ iamgeStyle } />;
    case "H-NYA": return <HNYA style={ iamgeStyle } />;
    case "H-NYU": return <HNYU style={ iamgeStyle } />;
    case "H-RYO": return <HRYO style={ iamgeStyle } />;
    case "H-SHA": return <HSHA style={ iamgeStyle } />;
    case "H-SHU": return <HSHU style={ iamgeStyle } />;
    case "H-CHO": return <HCHO style={ iamgeStyle } />;
    case "H-HYA": return <HHYA style={ iamgeStyle } />;
    case "H-HYU": return <HHYU style={ iamgeStyle } />;
    case "H-KYO": return <HKYO style={ iamgeStyle } />;
    case "H-MYA": return <HMYA style={ iamgeStyle } />;
    case "H-MYU": return <HMYU style={ iamgeStyle } />;
    case "H-NYO": return <HNYO style={ iamgeStyle } />;
    case "H-RYA": return <HRYA style={ iamgeStyle } />;
    case "H-RYU": return <HRYU style={ iamgeStyle } />;
    case "H-SHO": return <HSHO style={ iamgeStyle } />;
    // DARK
    case "H-CHA-DARK": return <HCHADARK style={ iamgeStyle } />;
    case "H-CHU-DARK": return <HCHUDARK style={ iamgeStyle } />;
    case "H-HYO-DARK": return <HHYODARK style={ iamgeStyle } />;
    case "H-KYA-DARK": return <HKYADARK style={ iamgeStyle } />;
    case "H-KYU-DARK": return <HKYUDARK style={ iamgeStyle } />;
    case "H-MYO-DARK": return <HMYODARK style={ iamgeStyle } />;
    case "H-NYA-DARK": return <HNYADARK style={ iamgeStyle } />;
    case "H-NYU-DARK": return <HNYUDARK style={ iamgeStyle } />;
    case "H-RYO-DARK": return <HRYODARK style={ iamgeStyle } />;
    case "H-SHA-DARK": return <HSHADARK style={ iamgeStyle } />;
    case "H-SHU-DARK": return <HSHUDARK style={ iamgeStyle } />;
    case "H-CHO-DARK": return <HCHODARK style={ iamgeStyle } />;
    case "H-HYA-DARK": return <HHYADARK style={ iamgeStyle } />;
    case "H-HYU-DARK": return <HHYUDARK style={ iamgeStyle } />;
    case "H-KYO-DARK": return <HKYODARK style={ iamgeStyle } />;
    case "H-MYA-DARK": return <HMYADARK style={ iamgeStyle } />;
    case "H-MYU-DARK": return <HMYUDARK style={ iamgeStyle } />;
    case "H-NYO-DARK": return <HNYODARK style={ iamgeStyle } />;
    case "H-RYA-DARK": return <HRYADARK style={ iamgeStyle } />;
    case "H-RYU-DARK": return <HRYUDARK style={ iamgeStyle } />;
    case "H-SHO-DARK": return <HSHODARK style={ iamgeStyle } />;

    case "K-A": return <KA style={ iamgeStyle } />;
    case "K-FU": return <KFU style={ iamgeStyle } />;
    case "K-HI": return <KHI style={ iamgeStyle } />;
    case "K-KA": return <KKA style={ iamgeStyle } />;
    case "K-KO": return <KKO style={ iamgeStyle } />;
    case "K-ME": return <KME style={ iamgeStyle } />;
    case "K-MU": return <KMU style={ iamgeStyle } />;
    case "K-NE": return <KNE style={ iamgeStyle } />;
    case "K-NU": return <KNU style={ iamgeStyle } />;
    case "K-RE": return <KRE style={ iamgeStyle } />;
    case "K-RU": return <KRU style={ iamgeStyle } />;
    case "K-SHI": return <KSHI style={ iamgeStyle } />;
    case "K-TA": return <KTA style={ iamgeStyle } />;
    case "K-TSU": return <KTSU style={ iamgeStyle } />;
    case "K-WE": return <KWE style={ iamgeStyle } />;
    case "K-YA": return <KYA style={ iamgeStyle } />;
    case "K-CHI": return <KCHI style={ iamgeStyle } />;
    case "K-HA": return <KHA style={ iamgeStyle } />;
    case "K-HO": return <KHO style={ iamgeStyle } />;
    case "K-KE": return <KKE style={ iamgeStyle } />;
    case "K-KU": return <KKU style={ iamgeStyle } />;
    case "K-MI": return <KMI style={ iamgeStyle } />;
    case "K-N": return <KN style={ iamgeStyle } />;
    case "K-NI": return <KNI style={ iamgeStyle } />;
    case "K-O": return <KO style={ iamgeStyle } />;
    case "K-RI": return <KRI style={ iamgeStyle } />;
    case "K-SA": return <KSA style={ iamgeStyle } />;
    case "K-SO": return <KSO style={ iamgeStyle } />;
    case "K-TE": return <KTE style={ iamgeStyle } />;
    case "K-U": return <KU style={ iamgeStyle } />;
    case "K-WI": return <KWI style={ iamgeStyle } />;
    case "K-YO": return <KYO style={ iamgeStyle } />;
    case "K-E": return <KE style={ iamgeStyle } />;
    case "K-HE": return <KHE style={ iamgeStyle } />;
    case "K-I": return <KI style={ iamgeStyle } />;
    case "K-KI": return <KKI style={ iamgeStyle } />;
    case "K-MA": return <KMA style={ iamgeStyle } />;
    case "K-MO": return <KMO style={ iamgeStyle } />;
    case "K-NA": return <KNA style={ iamgeStyle } />;
    case "K-NO": return <KNO style={ iamgeStyle } />;
    case "K-RA": return <KRA style={ iamgeStyle } />;
    case "K-RO": return <KRO style={ iamgeStyle } />;
    case "K-SE": return <KSE style={ iamgeStyle } />;
    case "K-SU": return <KSU style={ iamgeStyle } />;
    case "K-TO": return <KTO style={ iamgeStyle } />;
    case "K-WA": return <KWA style={ iamgeStyle } />;
    case "K-WO": return <KWO style={ iamgeStyle } />;
    case "K-YU": return <KYU style={ iamgeStyle } />;
    // Basic dark
    case "K-FU-DARK": return <KFUDARK style={ iamgeStyle } />;
    case "K-A-DARK": return <KADARK style={ iamgeStyle } />;
    case "K-HI-DARK": return <KHIDARK style={ iamgeStyle } />;
    case "K-KA-DARK": return <KKADARK style={ iamgeStyle } />;
    case "K-KO-DARK": return <KKODARK style={ iamgeStyle } />;
    case "K-ME-DARK": return <KMEDARK style={ iamgeStyle } />;
    case "K-MU-DARK": return <KMUDARK style={ iamgeStyle } />;
    case "K-NE-DARK": return <KNEDARK style={ iamgeStyle } />;
    case "K-NU-DARK": return <KNUDARK style={ iamgeStyle } />;
    case "K-RE-DARK": return <KREDARK style={ iamgeStyle } />;
    case "K-RU-DARK": return <KRUDARK style={ iamgeStyle } />;
    case "K-SHI-DARK": return <KSHIDARK style={ iamgeStyle } />;
    case "K-TA-DARK": return <KTADARK style={ iamgeStyle } />;
    case "K-TSU-DARK": return <KTSUDARK style={ iamgeStyle } />;
    case "K-WE-DARK": return <KWEDARK style={ iamgeStyle } />;
    case "K-YA-DARK": return <KYADARK style={ iamgeStyle } />;
    case "K-CHI-DARK": return <KCHIDARK style={ iamgeStyle } />;
    case "K-HA-DARK": return <KHADARK style={ iamgeStyle } />;
    case "K-HO-DARK": return <KHODARK style={ iamgeStyle } />;
    case "K-KE-DARK": return <KKEDARK style={ iamgeStyle } />;
    case "K-KU-DARK": return <KKUDARK style={ iamgeStyle } />;
    case "K-MI-DARK": return <KMIDARK style={ iamgeStyle } />;
    case "K-N-DARK": return <KNDARK style={ iamgeStyle } />;
    case "K-NI-DARK": return <KNIDARK style={ iamgeStyle } />;
    case "K-O-DARK": return <KODARK style={ iamgeStyle } />;
    case "K-RI-DARK": return <KRIDARK style={ iamgeStyle } />;
    case "K-SA-DARK": return <KSADARK style={ iamgeStyle } />;
    case "K-SO-DARK": return <KSODARK style={ iamgeStyle } />;
    case "K-TE-DARK": return <KTEDARK style={ iamgeStyle } />;
    case "K-U-DARK": return <KUDARK style={ iamgeStyle } />;
    case "K-WI-DARK": return <KWIDARK style={ iamgeStyle } />;
    case "K-YO-DARK": return <KYODARK style={ iamgeStyle } />;
    case "K-E-DARK": return <KEDARK style={ iamgeStyle } />;
    case "K-HE-DARK": return <KHEDARK style={ iamgeStyle } />;
    case "K-I-DARK": return <KIDARK style={ iamgeStyle } />;
    case "K-KI-DARK": return <KKIDARK style={ iamgeStyle } />;
    case "K-MA-DARK": return <KMADARK style={ iamgeStyle } />;
    case "K-MO-DARK": return <KMODARK style={ iamgeStyle } />;
    case "K-NA-DARK": return <KNADARK style={ iamgeStyle } />;
    case "K-NO-DARK": return <KNODARK style={ iamgeStyle } />;
    case "K-RA-DARK": return <KRADARK style={ iamgeStyle } />;
    case "K-RO-DARK": return <KRODARK style={ iamgeStyle } />;
    case "K-SE-DARK": return <KSEDARK style={ iamgeStyle } />;
    case "K-SU-DARK": return <KSUDARK style={ iamgeStyle } />;
    case "K-TO-DARK": return <KTODARK style={ iamgeStyle } />;
    case "K-WA-DARK": return <KWADARK style={ iamgeStyle } />;
    case "K-WO-DARK": return <KWODARK style={ iamgeStyle } />;
    case "K-YU-DARK": return <KYUDARK style={ iamgeStyle } />;
    // Dakuon
    case "K-BA": return <KBA style={ iamgeStyle } />;
    case "K-BI": return <KBI style={ iamgeStyle } />;
    case "K-BU": return <KBU style={ iamgeStyle } />;
    case "K-DE": return <KDE style={ iamgeStyle } />;
    case "K-DO": return <KDO style={ iamgeStyle } />;
    case "K-GA": return <KGA style={ iamgeStyle } />;
    case "K-GI": return <KGI style={ iamgeStyle } />;
    case "K-GU": return <KGU style={ iamgeStyle } />;
    case "K-ZA": return <KZA style={ iamgeStyle } />;
    case "K-ZO": return <KZO style={ iamgeStyle } />;
    case "K-BE": return <KBE style={ iamgeStyle } />;
    case "K-BO": return <KBO style={ iamgeStyle } />;
    case "K-DA": return <KDA style={ iamgeStyle } />;
    case "K-DJI": return <KDJI style={ iamgeStyle } />;
    case "K-DZU": return <KDZU style={ iamgeStyle } />;
    case "K-GE": return <KGE style={ iamgeStyle } />;
    case "K-GO": return <KGO style={ iamgeStyle } />;
    case "K-JI": return <KJI style={ iamgeStyle } />;
    case "K-ZE": return <KZE style={ iamgeStyle } />;
    case "K-ZU": return <KZU style={ iamgeStyle } />;
    // Dakuon dark
    case "K-BA-DARK": return <KBADARK style={ iamgeStyle } />;
    case "K-BI-DARK": return <KBIDARK style={ iamgeStyle } />;
    case "K-BU-DARK": return <KBUDARK style={ iamgeStyle } />;
    case "K-DE-DARK": return <KDEDARK style={ iamgeStyle } />;
    case "K-DO-DARK": return <KDODARK style={ iamgeStyle } />;
    case "K-GA-DARK": return <KGADARK style={ iamgeStyle } />;
    case "K-GI-DARK": return <KGIDARK style={ iamgeStyle } />;
    case "K-GU-DARK": return <KGUDARK style={ iamgeStyle } />;
    case "K-ZA-DARK": return <KZADARK style={ iamgeStyle } />;
    case "K-ZO-DARK": return <KZODARK style={ iamgeStyle } />;
    case "K-BE-DARK": return <KBEDARK style={ iamgeStyle } />;
    case "K-BO-DARK": return <KBODARK style={ iamgeStyle } />;
    case "K-DA-DARK": return <KDADARK style={ iamgeStyle } />;
    case "K-DJI-DARK": return <KDJIDARK style={ iamgeStyle } />;
    case "K-DZU-DARK": return <KDZUDARK style={ iamgeStyle } />;
    case "K-GE-DARK": return <KGEDARK style={ iamgeStyle } />;
    case "K-GO-DARK": return <KGODARK style={ iamgeStyle } />;
    case "K-JI-DARK": return <KJIDARK style={ iamgeStyle } />;
    case "K-ZE-DARK": return <KZEDARK style={ iamgeStyle } />;
    case "K-ZU-DARK": return <KZUDARK style={ iamgeStyle } />;
    // Handakuon
    case "K-PA": return <KPA style={ iamgeStyle } />;
    case "K-PE": return <KPE style={ iamgeStyle } />;
    case "K-PI": return <KPI style={ iamgeStyle } />;
    case "K-PO": return <KPO style={ iamgeStyle } />;
    case "K-PU": return <KPU style={ iamgeStyle } />;
    // Handakuon dark
    case "K-PA-DARK": return <KPADARK style={ iamgeStyle } />;
    case "K-PE-DARK": return <KPEDARK style={ iamgeStyle } />;
    case "K-PI-DARK": return <KPIDARK style={ iamgeStyle } />;
    case "K-PO-DARK": return <KPODARK style={ iamgeStyle } />;
    case "K-PU-DARK": return <KPUDARK style={ iamgeStyle } />;
    // 
    case "K-CHA": return <KCHA style={ iamgeStyle } />;
    case "K-CHU": return <KCHU style={ iamgeStyle } />;
    case "K-HYO": return <KHYO style={ iamgeStyle } />;
    case "K-KYA": return <KKYA style={ iamgeStyle } />;
    case "K-KYU": return <KKYU style={ iamgeStyle } />;
    case "K-MYO": return <KMYO style={ iamgeStyle } />;
    case "K-NYA": return <KNYA style={ iamgeStyle } />;
    case "K-NYU": return <KNYU style={ iamgeStyle } />;
    case "K-RYO": return <KRYO style={ iamgeStyle } />;
    case "K-SHA": return <KSHA style={ iamgeStyle } />;
    case "K-SHU": return <KSHU style={ iamgeStyle } />;
    case "K-CHO": return <KCHO style={ iamgeStyle } />;
    case "K-HYA": return <KHYA style={ iamgeStyle } />;
    case "K-HYU": return <KHYU style={ iamgeStyle } />;
    case "K-KYO": return <KKYO style={ iamgeStyle } />;
    case "K-MYA": return <KMYA style={ iamgeStyle } />;
    case "K-MYU": return <KMYU style={ iamgeStyle } />;
    case "K-NYO": return <KNYO style={ iamgeStyle } />;
    case "K-RYA": return <KRYA style={ iamgeStyle } />;
    case "K-RYU": return <KRYU style={ iamgeStyle } />;
    case "K-SHO": return <KSHO style={ iamgeStyle } />;
    // DARK
    case "K-CHA-DARK": return <KCHADARK style={ iamgeStyle } />;
    case "K-CHU-DARK": return <KCHUDARK style={ iamgeStyle } />;
    case "K-HYO-DARK": return <KHYODARK style={ iamgeStyle } />;
    case "K-KYA-DARK": return <KKYADARK style={ iamgeStyle } />;
    case "K-KYU-DARK": return <KKYUDARK style={ iamgeStyle } />;
    case "K-MYO-DARK": return <KMYODARK style={ iamgeStyle } />;
    case "K-NYA-DARK": return <KNYADARK style={ iamgeStyle } />;
    case "K-NYU-DARK": return <KNYUDARK style={ iamgeStyle } />;
    case "K-RYO-DARK": return <KRYODARK style={ iamgeStyle } />;
    case "K-SHA-DARK": return <KSHADARK style={ iamgeStyle } />;
    case "K-SHU-DARK": return <KSHUDARK style={ iamgeStyle } />;
    case "K-CHO-DARK": return <KCHODARK style={ iamgeStyle } />;
    case "K-HYA-DARK": return <KHYADARK style={ iamgeStyle } />;
    case "K-HYU-DARK": return <KHYUDARK style={ iamgeStyle } />;
    case "K-KYO-DARK": return <KKYODARK style={ iamgeStyle } />;
    case "K-MYA-DARK": return <KMYADARK style={ iamgeStyle } />;
    case "K-MYU-DARK": return <KMYUDARK style={ iamgeStyle } />;
    case "K-NYO-DARK": return <KNYODARK style={ iamgeStyle } />;
    case "K-RYA-DARK": return <KRYADARK style={ iamgeStyle } />;
    case "K-RYU-DARK": return <KRYUDARK style={ iamgeStyle } />;
    case "K-SHO-DARK": return <KSHODARK style={ iamgeStyle } />;

    default: return <HA style={ iamgeStyle } />;
  }
};

export default getImage;